javalinThreeVersion: 3.13.13
javalinFourVersion: 4.6.7
javalinFiveVersion: 5.6.4
javalinSixVersion: 6.7.0
javalinversion: 7.0.0
slf4jversion: 2.0.17
repourl: https://github.com/javalin/website
description: Javalin - A lightweight Java and Kotlin web framework. Create REST APIs in Java or Kotlin easily.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
